fixtures:
  repositories:
    concat: https://github.com/puppetlabs/puppetlabs-concat.git
    selinux: https://github.com/camptocamp/puppet-selinux.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
  symlinks:
    nagios: "#{source_dir}"
